import type { Opportunity, Researcher } from "@/lib/types";

export const currentResearcher: Researcher = {
  id: "researcher-current",
  slug: "dr-maya-chen",
  name: "Dr. Maya Chen",
  initials: "MC",
  role: "Translational Oncology Researcher",
  institution: "Charité – Universitätsmedizin Berlin",
  location: "Berlin, Germany",
  bio: "Translational researcher studying tumor–immune interactions and biomarker-guided therapeutic response in solid tumors.",
  verified: true,
  collaborationOpen: true,
  topics: ["Tumor immunology", "Precision oncology", "Biomarkers"],
  methods: ["Single-cell RNA-seq", "Spatial transcriptomics", "Clinical cohorts"],
  publications: 24,
  citations: "1.8k",
  currentFocus: "Mechanisms of immune escape in therapy-resistant solid tumors",
};

export const researchers: Researcher[] = [
  {
    id: "r-1",
    slug: "elena-rossi",
    name: "Prof. Elena Rossi",
    initials: "ER",
    role: "Principal Investigator · Cancer Immunology",
    institution: "European Institute of Oncology",
    location: "Milan, Italy",
    bio: "Investigates T-cell dysfunction, immune checkpoint resistance, and translational immunotherapy biomarkers.",
    verified: true,
    collaborationOpen: true,
    topics: ["Tumor immunology", "T-cell exhaustion", "Immunotherapy"],
    methods: ["Single-cell RNA-seq", "Flow cytometry", "CRISPR screens"],
    publications: 61,
    citations: "8.4k",
    currentFocus: "Reversing T-cell exhaustion in checkpoint-resistant tumors",
  },
  {
    id: "r-2",
    slug: "jonas-weber",
    name: "Dr. Jonas Weber",
    initials: "JW",
    role: "Group Leader · Computational Oncology",
    institution: "DKFZ",
    location: "Heidelberg, Germany",
    bio: "Builds multimodal models that connect genomic, spatial, and clinical data to treatment response.",
    verified: true,
    collaborationOpen: true,
    topics: ["Precision oncology", "Cancer genomics", "Clinical AI"],
    methods: ["Multimodal ML", "Spatial omics", "Survival analysis"],
    publications: 38,
    citations: "4.9k",
    currentFocus: "Interpretable multimodal prediction of therapy response",
  },
  {
    id: "r-3",
    slug: "aisha-rahman",
    name: "Dr. Aisha Rahman",
    initials: "AR",
    role: "Clinician Scientist · Thoracic Oncology",
    institution: "The Francis Crick Institute / UCLH",
    location: "London, UK",
    bio: "Runs longitudinal clinical studies of minimal residual disease and immune response in lung cancer.",
    verified: true,
    collaborationOpen: true,
    topics: ["Lung cancer", "Liquid biopsy", "Clinical trials"],
    methods: ["ctDNA", "Prospective cohorts", "Translational trials"],
    publications: 29,
    citations: "3.2k",
    currentFocus: "Early relapse detection using longitudinal ctDNA",
  },
  {
    id: "r-4",
    slug: "samuel-okafor",
    name: "Dr. Samuel Okafor",
    initials: "SO",
    role: "Postdoctoral Fellow · Systems Immunology",
    institution: "Karolinska Institutet",
    location: "Stockholm, Sweden",
    bio: "Studies immune-cell state transitions using perturbation experiments and single-cell multi-omics.",
    verified: true,
    collaborationOpen: true,
    topics: ["Systems immunology", "Cell state", "Multi-omics"],
    methods: ["CITE-seq", "Perturb-seq", "Network inference"],
    publications: 14,
    citations: "1.1k",
    currentFocus: "Perturbation maps of exhausted immune-cell states",
  },
];

export const opportunities: Opportunity[] = [
  {
    id: "o-1",
    slug: "postdoc-spatial-immuno-oncology",
    kind: "Postdoc",
    title: "Postdoctoral Fellow — Spatial Immuno-Oncology",
    institution: "Netherlands Cancer Institute",
    lab: "Tumor Microenvironment Program",
    location: "Amsterdam, Netherlands",
    remote: false,
    deadline: "Oct 28, 2026",
    funding: "3-year funded position",
    summary: "Map immune niches associated with therapy response using spatial transcriptomics and matched clinical cohorts.",
    topics: ["Tumor immunology", "Spatial transcriptomics", "Biomarkers"],
    requirements: ["PhD in cancer biology, immunology or related field", "Single-cell or spatial omics experience", "Strong collaborative publication record"],
    featured: true,
  },
  {
    id: "o-2",
    slug: "erc-synergy-collaboration-resistance",
    kind: "Collaboration",
    title: "Multi-center cohort for immunotherapy resistance",
    institution: "European Oncology Consortium",
    lab: "Clinical Translational Network",
    location: "Europe · Multi-site",
    remote: true,
    deadline: "Nov 12, 2026",
    funding: "Data + sample access",
    summary: "Seeking translational teams to contribute matched tissue, blood, and outcome data to a harmonized resistance cohort.",
    topics: ["Immunotherapy", "Clinical cohorts", "Resistance"],
    requirements: ["Access to longitudinal patient cohorts", "Ethics-compatible data contribution", "Named scientific lead"],
  },
  {
    id: "o-3",
    slug: "phd-computational-pathology",
    kind: "PhD",
    title: "PhD — Computational Pathology for Precision Oncology",
    institution: "ETH Zürich",
    lab: "Biomedical Data Science Lab",
    location: "Zürich, Switzerland",
    remote: false,
    deadline: "Dec 01, 2026",
    funding: "Fully funded · 4 years",
    summary: "Develop interpretable multimodal models combining histopathology, genomics, and clinical variables.",
    topics: ["Clinical AI", "Precision oncology", "Computational pathology"],
    requirements: ["MSc in computational or biomedical field", "Python/ML experience", "Interest in interpretable clinical AI"],
  },
  {
    id: "o-4",
    slug: "fellowship-translational-oncology",
    kind: "Fellowship",
    title: "Translational Oncology Fellowship 2027",
    institution: "Cancer Research UK",
    lab: "Independent Fellowship Program",
    location: "United Kingdom",
    remote: false,
    deadline: "Jan 19, 2027",
    funding: "Salary + research costs · up to 5 years",
    summary: "Protected transition funding for early-career researchers establishing an independent translational oncology program.",
    topics: ["Translational oncology", "Clinical research", "Independent fellowship"],
    requirements: ["Eligible host institution", "Strong translational research proposal", "Evidence of research independence"],
  },
];

export const activity = [
  { title: "New opportunity alignment", detail: "NKI spatial immuno-oncology postdoc matches your methods and research focus.", time: "18 min ago" },
  { title: "Researcher profile updated", detail: "Prof. Elena Rossi added a new project on checkpoint-resistant tumors.", time: "2 h ago" },
  { title: "Introduction accepted", detail: "Dr. Jonas Weber accepted your private introduction request.", time: "Yesterday" },
];
